### ISSUE TITLE
Spelling mistake: change oepn-source projects to open-source projects

### ISSUE THREAD

**Issue by adinetech** [NithishCodez/NithishCodez#1]
Hello,

i see that your https://github.com/NithishCodez/NithishCodez repository has a spelling mistake in readme.md file. 

You actually used **oepn-source projects** instead of **open-source projects**, so you know better fix it!

**Comment by NithishCodez** [comment]
Thanks sar, fixing it

**Comment by adinetech** [comment]
Ok sar.
